/* eslint-disable */
// Do not edit this file, it is auto-generated at build time!
// See scripts/bootstrap.ts to modify the generation of this file.
const config = {};
config.sitecoreApiKey = process.env.SITECORE_API_KEY || "{A0C26E61-7FA6-4732-8A61-FDCFA5E16774}",
config.sitecoreApiHost = process.env.SITECORE_API_HOST || "https://sc1020jss20edge.local",
config.jssAppName = process.env.JSS_APP_NAME || "nextjs-ssg",
config.graphQLEndpointPath = process.env.GRAPH_QL_ENDPOINT_PATH || "/sitecore/api/graph/edge",
config.defaultLanguage = process.env.DEFAULT_LANGUAGE || "en",
config.graphQLEndpoint = process.env.GRAPH_QL_ENDPOINT || `${config.sitecoreApiHost}${config.graphQLEndpointPath}`;
module.exports = config;